# Generated by Django 5.2.14 on 2026-05-21 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('barbeiro', models.ForeignKey(limit_choices_to={'tipo': 'barbeiro'}, on_delete=django.db.models.deletion.RESTRICT, related_name='agendamentos_barbeiro', to='perfil.perfil')),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.RESTRICT, related_name='agendamentos_cliente', to='perfil.perfil')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agendamentos_servico', to='barbearia.servico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('barbeiro', 'data_hora'), name='unique_agendamento_barbeiro_data_hora')],
            },
        ),
    ]
